### PR TITLE
Change intro paragraph to highlight ACL co-location

### PR DESCRIPTION
**Pull request by j0ma**
I changed the title in the metadata; that should add it as a `<h1>` level header.

### CODE REVIEW

**Comment by j0ma** [comment]
Let's not merge yet let me preview first once I figure how to get it to show at [https://j0ma.github.io](https://j0ma.github.io)

**Comment by mehmetoguzderin** [comment]
I thought idea was to add a paragraph to top while keeping brevity of the title, when we discussed with @varie a week ago or sth during the SIGTURK Weekly.

**Comment by j0ma** [comment]
:+1: Right, I'll edit!

**Comment by j0ma** [comment]
Alright:

:heavy_check_mark:  Title is the same as before: `Workshop`
:heavy_check_mark: First paragraph mentions co-location with ACL
:heavy_check_mark: First paragraph includes hyperlink to main ACL conference site to make things extra-clear

**Comment by j0ma** [comment]
To preview see [here](https://j0ma.github.io/preview/fix-acl-affiliation/workshop/)

**Review by mehmetoguzderin — APPROVED** [review]

**Comment by j0ma** [comment]
Perfect, thanks merging @mehmetoguzderin !

**Pull request merged**
