### PR TITLE
Website fixes for 2nd CFP

### PR DESCRIPTION
**Pull request by j0ma**
This PR implements changes to the SIGTURK workshop website that clarify organizational details.

The following changes were made

- Removed note about sponsorship funds
- Removed note about shared task
- Clarified hybrid nature of the event

### CODE REVIEW

**Comment by j0ma** [comment]
This will close https://github.com/sigturk/sigturk/issues/106

**Comment by mehmetoguzderin** [comment]
Good one, @j0ma ! Could you resolve the branch conflict for us to have a smoother review experience?

P.S.: You can just request review from @sigturk/officers-team and it will send notis to all officers.

**Comment by mehmetoguzderin** [comment]
(and other officials)

**Comment by j0ma** [comment]
Noted re: review request! Hmm I'll take a look at the conflicting txt file

**Review by mehmetoguzderin — APPROVED** [review]
IMO looks good!

**Comment by j0ma** [comment]
Perfect, merging.

**Pull request merged**
